version: "2"

services:
    mariadb:
        image: mariadb:latest
        volumes:
            - ./mariadb-data/:/var/lib/mysql/
            - ./mariadb-init-data/:/docker-entrypoint-initdb.d/
        #env_file:
            #- ./docker-env
        environment:
            - MYSQL_ROOT_PASSWORD=tourdejob.vn
            - MYSQL_USER=tourdejob
            - MYSQL_PASSWORD=tourdejob.vn
            - MYSQL_DATABASE=crawl_fb
        ports:
            - "3306:3306"
        networks:
            - back
        hostname: mariadb
        #domainname: eggclub.org
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 1073741824       # 1024 MB RAM
        # memswap_limit: 0            # 0 MB SWAP
        # privileged: true
        # restart: always
        # stdin_open: true
        tty: true

#volumes:
    #backend-data:
    #mysql-data:

networks:
    #front:
    back: